name: bip4

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - bip4network
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_ADMIN_PASS}
    ports:
      - ${POSTGRES_ADMIN_PORT}:80
    depends_on:
      - postgres
    networks:
      - bip4network
    configs:
      - source: pgadmin_servers
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgadmin4/pgpass
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin:root /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "q

  
configs:
  pgadmin_servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Obligatorio BI",
            "Group": "Servers",
            "Host": "postgres",
            "Port": 5432,
            "MaintenanceDB": "${POSTGRES_DB}",
            "Username": "${POSTGRES_USER}",
            "SSLMode": "prefer",
            "PassFile": "/var/lib/pgadmin/pgpass"
          }
        }
      }
  pgpass:
    content: |
      postgres:5432:${POSTGRES_DB}:${POSTGRES_USER}:${POSTGRES_PASS} 

networks:
  bip4network:
    driver: bridge